apiVersion: v1
kind: Service
metadata:
  name: {{ include "restapp.fullname" . }}
  labels:
    {{- include "restapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
  selector:
    {{- include "restapp.selectorLabels" . | nindent 4 }}
